### ISSUE TITLE
是否兼容ubuntu 64的，汉化后返回502错误

### ISSUE THREAD

**Issue by qyh214** [marbleqi/gitlab-ce-zh#1]
尝试按照汉化的做法，返回502错误页面，502错误页面是汉化后的
另外版本是GitLab Community Edition 8.13.5 09cedb5
ubuntu上也有这个路径啊，并且内容互相相符，不过社区版用的不是源码版，而是一键安装版，就是推荐的那个下载……

**Comment by marbleqi** [comment]
昨天（2016年11月15日）的覆盖版存在缺陷，现在已经修复重新发布。
有关汉化的步骤针对不同操作系统，但同一GitLab版本的操作应该是一致的。
按照如下步骤操作即可：
1. 下载汉化包后上传服务器后解压。[下载链接](https://github.com/marbleqi/gitlab-ce-zh/archive/8-13-5-zh-rel.zip)

2. 停止Gitlab服务。

    sudo gitlab-ctl stop
    
3. 备份服务器上的/opt/gitlab/embedded/service/gitlab-rails目录。
注：该目录下的内容主要是web应用部分，也是当前项目仓库的起始版本，也是汉化包要覆盖的目录。
    
4. 将解压后的汉化包覆盖服务器上的/opt/gitlab/embedded/service/gitlab-rails目录。

5. 启动Gitlab服务。

    sudo gitlab-ctl start

6. 重新执行配置命令。

    sudo gitlab-ctl reconfigure

完成上述步骤即实现汉化。
