### ISSUE TITLE
500 error

### ISSUE THREAD

**Issue by lingfengchencn** [marbleqi/gitlab-ce-zh#2]
安装完成后，会出现500。

哇，因为我们的原因发生错误。

**Comment by marbleqi** [comment]
看看版本是不是一致，包括操作系统，gitlab版本等。

**Comment by tangck** [comment]
centos 6.7 64bit    gitlab-ce-9.0.0-ce.0.el6.x86_64.rpm

gitlab-ce-zh-9.0.0-zh-patch    按照教程操作之后,也出现500错误

**Comment by lingfengchencn** [comment]
+1

嗯，完全按照操作来的。ce 9.0

**Comment by boneq** [comment]
我也是500错误用不了

**Comment by ldy321** [comment]
我也是500错误，没装汉化包可以连上 版本跟汉化包、教程步骤都是按楼主的git操作的，求指教centos7.2

**Comment by cuifeixiang** [comment]
我的也是500，
centos6.4  gitlab-ce.9.0.0

**Comment by ahmu** [comment]
相同问题，大家不要再踩坑了
centos6.5   gitlab-ce.9.0.0

**Comment by marbleqi** [comment]
建议大家绕过此版本。

**Comment by ly827** [comment]
建议大家绕过此版本 +1

**Comment by alnmp** [comment]
在踩一次坑 囧, 麻烦作者了

**Comment by luisxin** [comment]
啊啊。同样换成9.0.0.0出现500错误了。

**Comment by ssdutnowind** [comment]
才看到有500错误的问题，我也是打完补丁就500了T_T

**Comment by Password2008** [comment]
ActionView::Template::Error (undefined method `map' for "translation missing: zh.date.order":String

**Comment by Password2008** [comment]
修改了config.i18n.enforce_available_locales = false 后，很多功能都正常，但消息页面还是返回500，日志显示：ActionView::Template::Error (undefined method `map' for "translation missing: zh.date.order":String
Did you mean?  tap):
